### PR TITLE
fix: change default value to true for critical switch

### LINKED ISSUE #4647: [NV-2902] bug: new workflow is critical by default
### What?

Critical workflow overrides above the workflow and subscriber preference

### Why? (Context)

Steps to reproduce:-

1. Create a new workflow
2. Add any channel / action step
3. update the workflow
4. go to settings, workflow is critical by default.
5. **Users will be able to manage subscriptions** toggle button is off

Definition of Done

It should not be critical by default as a new user is not aware about critical concept. User get confused why subscriber preference is not working?

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-2902](https://linear.app/novu/issue/NV-2902/bug-new-workflow-is-critical-by-default)</sub>

### PR DESCRIPTION
**Pull request by jainpawan21**
### What change does this PR introduce?

Closes #4647

### CODE REVIEW

File: apps/web/src/pages/templates/components/TemplateEditorFormProvider.tsx [hunk 1]
```diff
@@ -112,7 +112,7 @@ const defaultValues: IForm = {
   description: '',
   identifier: '',
   tags: [],
-  critical: false,
```
Comment (jainpawan21) [inline apps/web/src/pages/templates/components/TemplateEditorFormProvider.tsx:115]: changed default value to true so that switch button for critical option is on and workflow is created non-critical

File: apps/web/src/pages/templates/components/notification-setting-form/TemplatePreference.tsx [hunk 2]
```diff
@@ -49,6 +49,7 @@ export function ChannelPreference() {
                     borderRadius: 8,
                   }}
                   position="apart"
+                  key={key}
```
Comment (jainpawan21) [inline apps/web/src/pages/templates/components/notification-setting-form/TemplatePreference.tsx:52]: Added this key filed to remove console unique key react error

**Review by scopsy — APPROVED** [review]
