### PR TITLE
Nv 942 bug report no way to reset destroy the

### LINKED ISSUE #1289: 🐛 Bug Report: No way to reset / destroy the `widget_user_auth_token` in the iFrame embed.
### 📜 Description

I have a Vue app that embeds the iFrame option for displaying the notification center. When I log out the existing user and log in as a new user, the notifications don't get updated. 

The `widget_user_auth_token` is not reset and remains the same. Only after a hard refresh on the page does the notification list update. 

### 👟 Reproduction steps

1. Embed the iFrame in your app.
2. Log in & check the notification center (also see `widget_user_auth_token`).
3. Log out of the current user.
4. log in as a new user.
5. Check the notification center (and `widget_user_auth_token`).

### 👍 Expected behavior

Step 5 should result in different notifications (and `widget_user_auth_token`) from step 2.

### 👎 Actual Behavior with Screenshots

Both the notifications and `widget_user_auth_token` for steps 2 and for remaining the same. 

### 💻 Operating system

MacOS

### 🤖 Node Version

16.4

### 📃 Provide any additional context for the Bug.

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

_No response_

### PR DESCRIPTION
**Pull request by BiswaViraj**
### What change does this PR introduce?

closes #1289 

- Added a logout method that removes the widget auth token, disconnects the WebSocket

### CODE REVIEW

File: packages/notification-center/src/shared/interfaces/index.ts [hunk 1]
```diff
@@ -89,6 +89,7 @@ export interface INovuProviderContext {
   fetchingStrategy: IFetchingStrategy;
   setFetchingStrategy: (strategy: Partial<IFetchingStrategy>) => void;
   onLoad: (data: { organization: IOrganizationEntity }) => void;
+  logout: VoidFunction;
```
Comment (p-fernandez) [inline packages/notification-center/src/shared/interfaces/index.ts:92]: Is this a TypeScript built in type for void functions? I didn't know about it.

**Review by p-fernandez — APPROVED** [review]
🌟
