### PR TITLE
fix: export TriggerRecipientsTypeEnum in Node.js SDK

### LINKED ISSUE #3786: 🐛 Bug Report: TriggerRecipientsTypeEnum is not exported.
### 📜 Description

I cannot trigger notification to multiple recipients in TypeScript app with Novu Node.js SDK, because **TriggerRecipientsTypeEnum** is required but not exported.

### 👟 Reproduction steps

1. add Novu SDK for Node.js to any TypeScript project. My app is normal NestJS, just generated with CLI and default `tsconfig.json`.
2. Try to trigger enum to multiple recipients:

```ts
await this.novu.trigger('some-workflow', {
      to: [{ type: 'Topic', topicKey: key }],
      payload: {}
    });
```

> TS Error: **Type '"Topic"' is not assignable to type 'TriggerRecipientsTypeEnum.TOPIC'**

3. Cannot run app

### 👍 Expected behavior

I should be able to import `TriggerRecipientsTypeEnum` from `@novu/node`.

### 👎 Actual Behavior with Screenshots

Here is current behavior of TypeScript client with Novu Node.js SDK:

ts

I cannot import this enum, because it is not exported.

ts2

### 📃 Provide any additional context for the Bug.

- Windows 11
- Node v18.12.1
- npm 8.19.2
- Visual Studio Code

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by michaldziuba03**
### What change does this PR introduce?
Exports `TriggerRecipientsTypeEnum` and remove some random unused imports inside SDK.

### Why was this change needed?
Because I was unable to use Novu Node.js SDK inside TypeScript project (without `//@ts-ignore` what I want avoid for sure in my apps)

Closes #3786

### CODE REVIEW

File: packages/node/src/index.ts [hunk 1]
```diff
@@ -12,6 +12,7 @@ export {
   TextAlignEnum,
   EmailBlockTypeEnum,
   ChannelTypeEnum,
+  TriggerRecipientsTypeEnum,
```
Comment (michaldziuba03) [inline packages/node/src/index.ts:15]: export missing enum

File: packages/node/src/lib/events/events.interface.ts [hunk 2]
```diff
@@ -1,6 +1,5 @@
 import {
   DigestUnitEnum,
-  IAttachmentOptions,
```
Comment (michaldziuba03) [inline packages/node/src/lib/events/events.interface.ts:3]: unused import

File: packages/node/src/lib/topics/topic.interface.ts [hunk 3]
```diff
@@ -1,10 +1,4 @@
-import {
-  ExternalSubscriberId,
-  ITopic,
-  TopicKey,
-  TopicName,
-  TriggerRecipientsTypeEnum,
-} from '@novu/shared';
+import { ExternalSubscriberId, TopicKey, TopicName } from '@novu/shared';
```
Comment (michaldziuba03) [inline packages/node/src/lib/topics/topic.interface.ts:2]: `ITopic` and `TriggerRecipientsTypeEnum` were unused + lint for 3 imports

**Review by p-fernandez — APPROVED** [review]
🌟
