### PR TITLE
fix(provider): Remove sender name field and make boolean type a switch in nodemailer

### LINKED ISSUE #1753: 🐛 Bug Report: nodemailer sendername field & secure field
### 📜 Description

1. Nodemailer has a `Sender name` field in UI, even though it's not used in 
https://github.com/novuhq/novu/blob/2ee01b8c97d77b9f3295e46720385c137a0bfd57/providers/nodemailer/src/lib/nodemailer.provider.ts
image

2. Secure field is a textfield, therefore not intuitive, user should leave this field empty if it's `false` and provide some value if `true`

### 👟 Reproduction steps

1. Go to integration Store
2. Click on Nodemailer integration

- Check https://github.com/novuhq/novu/blob/2ee01b8c97d77b9f3295e46720385c137a0bfd57/providers/nodemailer/src/lib/nodemailer.provider.ts

### 👍 Expected behavior

1. There should be no `Sender name` field in UI.
2. Secure field should be checkbox or switch 

### 👎 Actual Behavior with Screenshots

image
image

### 💻 Operating system

MacOS

### 🤖 Node Version

v16.14.2

### 📃 Provide any additional context for the Bug.

From my point of view it's better to rename it to custom SMTP connection and not Nodemailer :)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by peoray**
### Why was this change needed?

Closes #1753

### CODE REVIEW

File: libs/shared/src/consts/providers/credentials/provider-credentials.ts [hunk 1]
```diff
@@ -181,7 +181,7 @@ export const nodemailerConfig: IConfigCredentials[] = [
     type: 'string',
     required: false,
   },
-  ...mailConfigBase,
+  mailConfigBase[0],
```
Comment (p-fernandez) [inline libs/shared/src/consts/providers/credentials/provider-credentials.ts:184]: I consider we shouldn't remove the option to set the sender name from Nodemailer. If it is not used in the provider package we should implement it. Probably the change for the credentials would be to make the sender name optional instead of mandatory as it is right now.

File: apps/web/src/pages/integrations/components/IntegrationInput.tsx [hunk 2]
```diff
@@ -73,6 +73,28 @@ export function IntegrationInput({
...
+        placeholder={credential.displayName}
+        description={credential.description ?? ''}
+        data-test-id={credential.key}
+        error={errors[credential.key]?.message}
+        {...register(credential.key)}
+        checked={field.value}
+        onChange={field.onChange}
+      />
+    );
+  }
```
Comment (p-fernandez) [inline apps/web/src/pages/integrations/components/IntegrationInput.tsx:96]: This change will make all boolean values for all integrations to become a Switch. We should review all the providers to see nothing breaks in the functionality.
Adding screenshots of how they would look like now would be also helpful for the PR reviewers.

Comment (peoray) [reply apps/web/src/pages/integrations/components/IntegrationInput.tsx:96]: yes, although, it makes sense for a boolean to be a toggle rather than an input field. I know I have been confused by that when creating documentation for ([sparkpost](https://docs.novu.co/channels/email/sparkpost/)). 

The only providers affected are Sparkpost and Nodemailer (I checked). The others have a type of switch, which frankly I don't understand why it is so, `boolean` sounds like a better option since it's only true or false. (Note that this switch type is only included in the nodemailer config as well so it's the same behaviour as the boolean.

**Comment by peoray** [comment]
Screen Shot 2023-05-09 at 10 30 54 AM
@p-fernandez

**Review by p-fernandez — APPROVED** [review]
🌟 
Well done!

**Comment by p-fernandez** [comment]
@peoray could you do a `pnpm install` and `pnpm build` in your branch and commit the changes? The lock file is not working as expected and blocking the CI. 🙏🏻

**Comment by peoray** [comment]
@p-fernandez done
