### PR TITLE
fix: integrations store stretching

### LINKED ISSUE #1816: 🐛 Bug Report: Integrations Store responsive design issue
## On small width devices & browser windows list of integrations looks weird:

https://user-images.githubusercontent.com/87207122/197292568-66a3739e-c3e7-4457-99c0-77c2059cd0b0.mov

## I created a solution, which use only `Mantine API` without changing any other props:

https://user-images.githubusercontent.com/87207122/197293109-19230744-cdf3-4494-ab61-b98f44da9122.mov

### 👟 Reproduction steps

1. Go [here](https://web.novu.co/integrations).
2. Use `Device Toolbar` or just change width of your browser window.

### 👍 Expected behavior

It should stretch normally without going outside of the window.

### 👎 Actual Behavior with Screenshots

***Only videos ⬆️***

### 💻 Operating system

MacOS

### 🤖 Node Version

18.10.0

### 📃 Provide any additional context for the Bug.

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by MaximFedarau**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fix #1816

- **Why was this change needed?** (You can also link to an open issue here)
Because the change makes this website section more smooth and accurate.

## Before:

https://user-images.githubusercontent.com/87207122/197418551-d8693a47-0d5c-4c32-a5d7-4193475dcfe3.mov

## After:

https://user-images.githubusercontent.com/87207122/197418564-455535f2-a8c5-498b-98e7-1cadd75616aa.mov

### CODE REVIEW

**Comment by MaximFedarau** [comment]
@scopsy, please, take a look😅

File: apps/web/src/pages/integrations/components/ChannelGroup.tsx [hunk 1]
```diff
@@ -18,15 +18,51 @@ export function ChannelGroup({
...
+          <div key={provider.providerId}>
+            <ProviderCard provider={provider} onConnectClick={handlerOnConnectClick} />
+          </div>
+        ))}
+      </ContentWrapper>
+    </Wrapper>
   );
 }
+
+const LAYOUT_GAP = 25;
```
Comment (scopsy) [inline apps/web/src/pages/integrations/components/ChannelGroup.tsx:36]: Love the variable usage here!

File: apps/web/src/pages/integrations/components/ChannelGroup.tsx [hunk 2]
```diff
@@ -18,15 +18,51 @@ export function ChannelGroup({
...
-      ))}
-    </Grid>
+      </div>
+      <ContentWrapper>
+        {providers.map((provider) => (
+          <div key={provider.providerId}>
+            <ProviderCard provider={provider} onConnectClick={handlerOnConnectClick} />
+          </div>
+        ))}
+      </ContentWrapper>
```
Comment (scopsy) [inline apps/web/src/pages/integrations/components/ChannelGroup.tsx:31]: A small question, I think it would be better to have the native mantine implementation here rather than a custom grid. Any particular reason it was needed, seems you got it to work on your first PR with this approach.

**Review by scopsy — COMMENTED** [review]
Thank you so much @MaximFedarau, added a small question regarding the grid usage by mantine let me know what you think

File: apps/web/src/pages/integrations/components/ChannelGroup.tsx (hunk 2 above)
Comment (MaximFedarau) [reply apps/web/src/pages/integrations/components/ChannelGroup.tsx:31]: Hi.
The first option, using Mantine, works, but it is not smooth enough as the second one. 
So, watch the second and the third video in the issue and respond: which option is the best for you?

**Comment by MaximFedarau** [comment]
Hey, @scopsy. Answered your questions!😁

**Comment by MaximFedarau** [comment]
Hey, @scopsy . Anwered your question. Please, send some feedback, so issue can be solved😄

File: apps/web/src/pages/integrations/components/ChannelGroup.tsx [hunk 3]
```diff
@@ -18,15 +18,51 @@ export function ChannelGroup({
...
 }
+
+const LAYOUT_GAP = 25;
+
+const Wrapper = styled.div`
+  display: flex;
+  flex-direction: column;
+  gap: ${LAYOUT_GAP}px;
+  margin-bottom: 50px;
+`;
```
Comment (p-fernandez) [inline apps/web/src/pages/integrations/components/ChannelGroup.tsx:43]: I think here we can use `Container` from `import { Container } from '../../../design-system';`.
At the end `Container` is a wrapper around `Box` Mantine component that is implemented based on a `div`.

File: apps/web/src/pages/integrations/components/ChannelGroup.tsx [hunk 4]
```diff
@@ -18,15 +18,51 @@ export function ChannelGroup({
...
+
+const ContentWrapper = styled.div`
```
Comment (p-fernandez) [inline apps/web/src/pages/integrations/components/ChannelGroup.tsx:45]:
```suggestion
const ContentWrapper = styled(Container)`
```
Here the same, as I would expect the Mantine component to pass all the grid CSS properties to the `div` element. But not 100% sure.

File: apps/web/src/pages/integrations/components/ChannelGroup.tsx [hunk 5]
```diff
@@ -18,15 +18,51 @@ export function ChannelGroup({
   }
 
   return (
-    <Grid mb={50}>
-      <Grid.Col span={12} data-test-id={`integration-group-${title.toLowerCase()}`}>
+    <Wrapper>
+      <div data-test-id={`integration-group-${title.toLowerCase()}`}>
```
Comment (p-fernandez) [inline apps/web/src/pages/integrations/components/ChannelGroup.tsx:22]: This can be a component `Container` easily. 👍🏻

**Comment by MaximFedarau** [comment]
@p-fernandez, thanks for your review. It is very helpfull!
But I still need an answer which way is the best: create custom grid or use bare `Mantine` instead😁

**Comment by MaximFedarau** [comment]
Hey, @scopsy, please, take a look😅

**Comment by MaximFedarau** [comment]
Hey @scopsy, please, take a look)

**Comment by MaximFedarau** [comment]
Hey @scopsy, please, take a look)

**Comment by MaximFedarau** [comment]
@scopsy, please, take a look.

**Comment by scopsy** [comment]
@MaximFedarau I think using Mantine's Grid is the way to go rather than implementing our own grid. What do you think ?

**Comment by scopsy** [comment]
Let me know what you think, and when implemented let's merge 🎉

**Comment by MaximFedarau** [comment]
@scopsy, ok, I agree with you. It's better for:
1) newcomers;
2) code style, because we've already used `Mantine`.

**Comment by MaximFedarau** [comment]
@p-fernandez, @scopsy, please, take a look.

**Review by p-fernandez — APPROVED** [review]
