### PR TITLE
style: Fix UI issues in settings page

### LINKED ISSUE #840: UI issues in Settings menu, Branding Tab
**Describe the bug**
In "Settings" Menu, "Branding" tab:
* Logo is streched and not showing properly ( rendered size 80x100, original logo size: 512x512)
* I cannot input HEX code in the Brand color input field, quite impossible to get my brand color if not a standard one.
* The Font Family seems to be from Google Fonts, maybe better if we have a full list (or a search box) to choose the our own, the current selection is very limited.

**To Reproduce**
1. Go to 'Settings' menu from your account
2. Click on 'Branding' tab
3. Try to upload a square logo, change your brand color, choose a Font.

**Expected behavior**
Logo should be square (or with the same aspect ratio as uploaded)
Brand color input shall accept custom hex color code
Font family shall show a full Google Fonts list or provide a search box for search and select.

**Screenshots**
Screenshot 2022-07-13 at 20 37 14

**Details (please complete the following information):**
 - OS: Mac
- Live Novu platform

**Additional context**
None

### PR DESCRIPTION
**Pull request by TheLearneer**
## What kind of change does this PR introduce?
Fixes #840

- Updated image size to be 100x100 with `object-fit: contain` so that they always maintain the original aspect ratio if not square
- Makes it possible to input custom values in color picker; helpful especially when the required color is just too specific

## Why was this change needed?
This PR was introduced to fixes issue and introduce requested feature in the Setting page.

## Other information
As per the discussion over at Discord with @scopsy the issue with the font Select component is left as it.
This is because the mantine version used on the web is slightly older version. (Needs #1346)

### CODE REVIEW

File: apps/web/src/pages/settings/tabs/BrandingForm.tsx [hunk 1]
```diff
@@ -162,6 +162,7 @@ export function BrandingForm({
                   label="Brand Color"
                   description="Will be used to style emails and inbox experience"
                   data-test-id="color-picker"
+                  disallowInput={false}
```
Comment (p-fernandez) [inline apps/web/src/pages/settings/tabs/BrandingForm.tsx:165]: API reference: https://mantine.dev/core/color-input/#disable-free-input

**Review by p-fernandez — APPROVED** [review]
🌟
