### PR TITLE
Fix embed runtime env variables

### LINKED ISSUE #1249: 🐛 Bug Report: ENV for widget doesn't change anything
### 📜 Description

Using the docker compose with the newest version the widget always points to localhost:3500 and it's not changable with env variables.

### 👟 Reproduction steps

Use the docker compose setup for novu.
Change the ports for novu widget.
It will not work.

### 👍 Expected behavior

You should be able to change the urls for widget with envs.

### 👎 Actual Behavior with Screenshots

-

### 💻 Operating system

MacOS

### 🤖 Node Version

-

### 📃 Provide any additional context for the Bug.

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

_No response_

### PR DESCRIPTION
**Pull request by djabarovgeorge**
- **What kind of change does this PR introduce?** (Bug fix)
At the current state, the environment variables are embeded in the static page on rollup build (@rollup/plugin-replace), in this PR we added a build step so that rollup rebuild the environment variables.

- **Why this change was needed?** (You can also link to an open issue here)
While using the docker-compose environment the user will want to use the prebuilt images and update the environment variable in runtime (docker-compose up). 

- **Other information**:
Closes #1249 
Closes NV-895

### CODE REVIEW

File: scripts/pnpm-context.mjs [hunk 1]
```diff
@@ -169,7 +169,7 @@ async function getMetafilesFromPnpmSelector(selector, cwd, options = {}) {
 async function getPackagePathsFromPnpmSelector(selector, cwd) {
   const projects = await readProjects(cwd, [parsePackageSelector(selector, cwd)]);
 
-  return Object.keys(projects.selectedProjectsGraph).map((p) => relative(cwd, p).replaceAll('\\', '/'));
+  return Object.keys(projects.selectedProjectsGraph).map((p) => relative(cwd, p).replace(/\\/g, '/'));
```
Comment (djabarovgeorge) [inline scripts/pnpm-context.mjs:172]: In order to resolve "replaceAll is not a function".

https://www.designcise.com/web/tutorial/how-to-fix-replaceall-is-not-a-function-javascript-error

**Review by davidsoderberg — APPROVED** [review]
Oh nice catch 👍
