### PR TITLE
fix: mark-as-seen response dto

### LINKED ISSUE #2071: [NV-1234] 🐛 Bug Report: "Mark a Subscriber Message as Seen" now returns an array instead of an object
### 📜 Description

The [/subscribers/:subscriberId/messages/:messageId/seen](https://docs.novu.co/api/mark-a-subscriber-feed-message-as-seen/) used to return an object, as `{ data : message }`, but it now returns an array as `{ data: [ message ] }`. I've looked through the Novu 0.9.0 changelog and this doesn't seem intentional.

### 👟 Reproduction steps

Simply call the [/subscribers/:subscriberId/messages/:messageId/seen](https://docs.novu.co/api/mark-a-subscriber-feed-message-as-seen/) endpoint, and inspect the response!

### 👍 Expected behavior

```
{
      "_id": "7424330252f89d6dc2bd8dd9",
      "_templateId": "54333bb0c26b68d4d067c9",
      "_environmentId": "8765c40853b9b0393a2aad1a",
      "_messageTemplateId": "8765ce3bb0c26b68d4d067c1",
      "_notificationId": "0987330252f89d6dc2bd8dc9",
      "_organizationId": "1234c40853b9b0393a2aad07",
      "_subscriberId": "7410a44f517e174e9008hg43",
      "templateIdentifier": "novu-invite-to-an-organization",
      "email": "email@gmail.com",
      "subject": "[Novu] You are invited to join a Novu organization",
      "cta": {
          "action": {
              "buttons": []
          }
      },
      "channel": "email",
      "content": [
          {
              "type": "text",
              "content": "<span>Hi, We are inviting you to join Organization Name</span>",
              "styles": {
                  "textAlign": "left"
              },
              "url": ""
          },
          {
              "type": "button",
              "content": "Test Notification",
              "styles": {
                  "textAlign": "left"
              },
              "url": "https://novu.url/auth/invitation/xxx"
          }
      ],
      "providerId": "sendgrid",
      "deviceTokens": [],
      "seen": false,
      "status": "sent",
      "transactionId": "kj3kfd3k3j-b4cc-4805-b3c5-62889a8583a4",
      "payload": {
          "email": "email@gmail.com",
          "inviteeName": "Invitee Name",
          "organizationName": "Organization Name",
          "inviterName": "Inviter Name",
          "acceptInviteUrl": "https://novu.url/auth/invitation/1234353-3599-11ed-b2b0-b5195a81006f"
      },
      "createdAt": "2022-09-16T08:25:38.844Z",
      "updatedAt": "2022-09-16T08:25:38.844Z",
      "__v": 0
}
```

### 👎 Actual Behavior with Screenshots

```
{
    "data": [
        {
            "_id": "7424330252f89d6dc2bd8dd9",
            "_templateId": "54333bb0c26b68d4d067c9",
            "_environmentId": "8765c40853b9b0393a2aad1a",
            "_messageTemplateId": "8765ce3bb0c26b68d4d067c1",
            "_notificationId": "0987330252f89d6dc2bd8dc9",
            "_organizationId": "1234c40853b9b0393a2aad07",
            "_subscriberId": "7410a44f517e174e9008hg43",
            "templateIdentifier": "novu-invite-to-an-organization",
            "email": "email@gmail.com",
            "subject": "[Novu] You are invited to join a Novu organization",
            "cta": {
                "action": {
                    "buttons": []
                }
            },
            "channel": "email",
            "content": [
                {
                    "type": "text",
                    "content": "<span>Hi, We are inviting you to join Organization Name</span>",
                    "styles": {
                        "textAlign": "left"
                    },
                    "url": ""
                },
                {
                    "type": "button",
                    "content": "Test Notification",
                    "styles": {
                        "textAlign": "left"
                    },
                    "url": "https://novu.url/auth/invitation/xxx"
                }
            ],
            "providerId": "sendgrid",
            "deviceTokens": [],
            "seen": false,
            "status": "sent",
            "transactionId": "kj3kfd3k3j-b4cc-4805-b3c5-62889a8583a4",
            "payload": {
                "email": "email@gmail.com",
                "inviteeName": "Invitee Name",
                "organizationName": "Organization Name",
                "inviterName": "Inviter Name",
                "acceptInviteUrl": "https://novu.url/auth/invitation/1234353-3599-11ed-b2b0-b5195a81006f"
            },
            "createdAt": "2022-09-16T08:25:38.844Z",
            "updatedAt": "2022-09-16T08:25:38.844Z",
            "__v": 0
        }
    ]
}
```

### 💻 Operating system

Linux

### 🤖 Node Version

16

### 📃 Provide any additional context for the Bug.

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

_No response_

<sub>[NV-1234](https://linear.app/novu/issue/NV-1234/🐛-bug-report-mark-a-subscriber-message-as-seen-now-returns-an-array)</sub>

### PR DESCRIPTION
**Pull request by djabarovgeorge**
### What change does this PR introduce? 

fix the response of mark as seen.

### Why was this change needed?

Closes #2071

### CODE REVIEW

File: apps/api/src/app/subscribers/subscribers.controller.ts [hunk 1]
```diff
@@ -362,7 +362,7 @@ export class SubscribersController {
       mark: { [MarkEnum.SEEN]: true },
     });
 
-    return await this.markMessageAsUsecase.execute(command);
+    return (await this.markMessageAsUsecase.execute(command))[0];
```
Comment (p-fernandez) [inline apps/api/src/app/subscribers/subscribers.controller.ts:365]: Just a nit. Shouldn't be better to fix this inside of the usecase? I haven't found anywhere else where this usecase is being used than these 2 controllers you modified so it would make sense to me change it there. There was any problem to not be able to do that?

**Review by p-fernandez — APPROVED** [review]

File: apps/api/src/app/subscribers/subscribers.controller.ts (hunk 1 above)
Comment (djabarovgeorge) [reply apps/api/src/app/subscribers/subscribers.controller.ts:365]: Hey @p-fernandez  thanks for looking into it, i see that we use it in the subscribers controller on the route @Post('/:subscriberId/messages/markAs') and widget controller route   @Post('/messages/markAs'). IMO we can remove those `/seen` endpoints in the future because the `/markAs` is more generic in our case. LMKWYT.

Comment (p-fernandez) [reply apps/api/src/app/subscribers/subscribers.controller.ts:365]: I just noticed the deprecated endpoints. I guess we still can't remove them so do the change I propose would break current implementations. We could duplicate the use case to have one different for mark one message and mark multiple messages and rewire the endpoints as needed, but that's too much work for this PR. 😕
